import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#EDF3FF',
        borderEndColor: '#ccc',
        padding: 8,
    },
    title: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 16,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 16,
        margin: 8,
    },
    headerText: {
        color: '#24BCCA',
        fontSize: 20,
        fontWeight: 'bold',
        padding: 8,
    },
    logo: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    input: {
        fontSize: 16,
        backgroundColor: '#EDF3FF',
        borderColor: '#3ABFCB',
        borderWidth: 1,
        color: '#000',
        borderRadius: 8,
        padding: 16,
        marginHorizontal: 16,
        marginVertical: 8,
    },
    buttonContainer: {
        flexDirection: 'row',
        alignSelf: 'center',
        justifyContent: 'center',
        backgroundColor: '#40B8C3',
        borderRadius: 32,
        width: 100,
        margin: 8,
    },
    buttonDisabled: {
        flexDirection: 'row',
        alignSelf: 'center',
        justifyContent: 'center',
        backgroundColor: '#aaa',
        borderRadius: 32,
        width: 100,
        margin: 8,
    },
    button: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 8,
        marginVertical: 2,
    },
    buttonText: {
        fontSize: 16,
        color: '#eff',
    },
    buttonIcon: {
        color: '#eff',
    },
    todo: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#DBEDEFb9',
        padding: 10,
        marginVertical: 8,
        marginHorizontal: 16,
        borderRadius: 12,
        borderColor: 'rgba(55, 55, 55, 0.04)',
        borderWidth: 2,
    },
    checkbox: {
        padding: 8,
        marginLeft: 16,
        marginRight: 22,
    },
    completed: {
        fontSize: 16,
        textDecorationLine: 'line-through',
        color: 'gray',
    },
    uncompleted: {
        fontSize: 16,
    },
    filterOptions: {
        marginHorizontal: 12,
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    filterChipInactive: {
        borderWidth: 2,
        borderRadius: 8,
        borderColor: '#c5c5C5',
        padding: 8,
        margin: 8,
    },
    filterChipActive: {
        borderWidth: 2,
        borderRadius: 8,
        borderColor: '#24BCCA',
        padding: 8,
        margin: 8,
    },
    edit: {
        flex: 1,
        flexDirection: 'row',
    },
    editActions: {
        flexDirection: 'row',
        justifyContent: 'center',
        margin: 8,
    },
});
